#+title: blender-x-emacs
#+author: Oliver J. Mead <olivermead@olivermead.xyz>

The dream of true integration for Blender in GNU Emacs.

* Progress
A proof of concept! See [[#Goals][Goals]] and [[./NOTES.org::*Proof of Concept][NOTES.org:Proof of Concept]].

* Note on Links
In order to make the inter-page links work on the GitHub/CodeBerg
render of these files, they would not work locally in Emacs. We have
opted to keep them working in Emacs, sorry.

* TODO [1/7] Goals
See [[file:NOTES.org::*Emacs IRC][NOTES.org:Emacs IRC]], and below:
+ [X] 'Live' Scripting, with direct REPL integration
  + [X] Connect to a running Blender session to send python commands with [[https://github.com/masscollaborationlabs/blender_command_port][blender_command_port]]
  + [X] Wrap it with some elisp to use within Emacs (see [[./NOTES.org::*Proof of Concept][NOTES.org:Proof of Concept]])
+ [ ] Link to objects, materials, node groups, camera views, etc. in org-mode and org-capture
+ [ ] View and edit the object tree
+ [ ] Spreadsheet
  + [ ] View and edit the spreadsheet
  + [ ] potentially with live updates
+ [ ] View and edit render settings
+ [ ] Trigger rendering, both in batch mode and with the Blender GUI
+ [ ] Use TRAMP to run remote render jobs
